#test for git
# docker build 하기 전에 일어나는 행위
before_install:
  chmod +x mvnw
  #mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

language: java
install: true

os: linux
dist: trusty
jdk: 
 - openjdk8
 - openjdk11
